const BLOCK_GENERATION_INTERVAL = 10;

const DIFFICULTY_ADJUSMENT_INTERVAL = 10;

const COINBASE_AMOUNT = 50;

module.exports = {
    BLOCK_GENERATION_INTERVAL,
    DIFFICULTY_ADJUSMENT_INTERVAL,
    COINBASE_AMOUNT
};